name: artifacts and paths
on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: creating
        run: |
          echo "Hi This is a artitfact from abhi build" > build.txt
          echo "AIDIHFBdHAhHBABOQHWHC" > testing.txt

      - name: uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-test file
          path: |
            build.txt
            testing.txt

  Test-Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: download stage
        uses: actions/download-artifact@v4
        with:
          name: build-test file

      - name: test-deploy
        run: |
          cat build.txt
          cat testing.txt
          echo "workflow successful"
