name: composite-input
on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: person name
        uses: ./actions/input
        with:
          name: Abhi124
        
