name: matrix-build
on:
  workflow_dispatch: 

jobs:
  matrix-:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - windows
          - linux
          - mac os
        
        version:
          - 1
          - 2
          - 3
          
    steps:
      - name: show version
        run: |
          echo "Testing Version Is ${{ matrix.version }}"
          echo "Testing running on ${{ matrix.os }}"
