name: matrix-build
on:
  workflow_dispatch: 

jobs:
  matrix-:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        asach:
          - abhi
          - nitin
          - pranay
          
    steps:
      - name: show version
        run: echo "Testing Version Is ${{ matrix.asach }}"
