name: demo
on:
  workflow_dispatch:
  
jobs:

  generate:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Generate version
        id: version
        run: echo "version=1.2.3" >> "$GITHUB_OUTPUT"

  build:
    needs: generate
    runs-on: ubuntu-latest

    steps:
      - name: Show version
        run: echo "Building version ${{ needs.generate.outputs.version }}"
