name: reusable
on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo "This is Build stage"
      - name: test
        run: echo "This is test stage"
      
