name: runs-on-matrix

on:
  workflow_dispatch:

jobs:
  job-1:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node-version: "1.2"

          - os: windows-latest
            node-version: "1.4"

          - os: ubuntu-latest
            node-version: "1.1"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check Node version
        run: echo "Running on ${{ matrix.os }} with Node ${{ matrix.node-version }}"
