name: Secret-demo
on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret
        env: 
          DEMO_SECRET: ${{ secrets.DEMO }}

        run: |
          echo "Secret is available"
          'echo "${{ #DEMO_SECRET }}"'
