name: step fuction
on:
  workflow_dispatch: 

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Create Version
        id: ver
        run: echo "version = 3.0" >> "GITHUB_OUTPUT"

      - name: show version
        run: echo "${{ steps.ver.outputs.version }}"
        
