name: Step Outputs

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Generate version
        id: version
        run: echo "version=1.0.0" >> "$GITHUB_OUTPUT"

      - name: Show version
        run: 'echo "Version is ${{ steps.version.outputs.version }}"'
