name: step fuction
on:
  workflow_dispatch: 

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Create Version
        id: version
        run: echo "Version = 1.0.0" >> "GITHUB_OUTPUT"

      - name: show version
        run: 'echo "Version is: ${{ steps.version.outputs.version }}"'
        
