name: success & Fail
on:
  workflow_dispatch:

jobs:
  success-fail:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Fail
        if: failure()
        run: |
          echo "running tests"
          exit-1

      - name: Success
        if: success()
        run: echo "Tests passed"
        
