name: vars & secrets
on:
  workflow_dispatch: 

env:
  AWS_REGION: ap-south-1
  
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps: 
      - name: show aws region
        run: echo "AWS_REGION=${{ env.AWS_REGION }}"

      - name: show  secret
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          echo "SECRET:${SECRET}"
          
