name: workflow-call-resuable-input
on: 
  push:
    paths-ignore: 
      - "actions/**"
      - ".github/**"
  pull_request: 

jobs:
  ci-pipeline:
    uses: ./.github/workflows/reusable-node-input.yml

    with: 
      node-version: "20"
